config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :brands, only: [:show] do 
    resources :items
  end

  resources :categories, only: [:show] do
    resources :items
  end

  get '/items/sold', to: "items#sold"
  get '/brands/:id/list', to: "brands#list"

  resources :users, only: [:new,:create]
  get '/login', to: "sessions#new"
  post '/sessions', to: "sessions#create"
  post '/brands/:id/items/new', to: "items#create"
  get '/logout', to: "sessions#destroy"
  get '/auth/facebook/callback' => 'sessions#create'
  
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :items
    has_many :categories, :through => :items
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
    has_many :brands, :through => :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :category
    belongs_to :brand

    def category_name=(name)
        self.category= Category.find_or_create_by(name: name)
    end

    def category_name
        self.category ? self.category.name : nil
    end

     def brand_name=(name)
        self.brand = Brand.find_or_create_by(name: name)
    end

    def brand_name
        self.brand ? self.brand.name : nil
    end

    def self.sold
        where(sold:true)
    end

end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true 
    validates :email, uniqueness: true
    has_secure_password 

    def self.find_or_create_by_omniauth(auth_hash)
        self.where(email: auth_hash.extra.raw_info[:email]).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authentification_required
        if !logged_in?
            redirect_to login_path
        end
    end

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end
    
    helper_method :current_user

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :authentification_required
    def show
        @brand = Brand.find(params[:id])
        @item = Item.new
        respond_to do |f|
            f.html
            f.json {render json: @brand, status: 201}
        end 
    end

    def list
        @brand = Brand.find(params[:id])
        @items = @brand.items
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authentification_required

    def show
        @category = Category.find(params[:id])
        @item = Item.new
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authentification_required

    def create
        @item = Item.create(item_params)
        
        if (params[:brand_id])
            @brand = Brand.find(params[:brand_id])
        else 
            @brand = Brand.create(name: params[:brand_name])
        end
        render json: @item, status: 201

    end

    def show
        @item = Item.find(params[:id])
    end

    def sold
        @items = Item.sold
        render json: @items, status: 201
    end

    def new
        if(params[:brand_id])
            @brand = Brand.find(params[:brand_id])
        else
            @category = Category.find(params[:category_id])
        end
        @item = Item.new(brand_id: params[:brand_id])
    end

private 
    def item_params
        params.require(:item).permit(:name, :category_name, :brand_name, :color, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :layout => false
    end

    def create 
        if auth_hash = request.env["omniauth.auth"]
            user = User.find_or_create_by_omniauth(auth_hash)
            session[:user_id] = user.id
            redirect_to root_path
        else
            user = User.find_by(email: params[:email])
            if user && user.authenticate(params[:password])
                session[:user_id] = user.id
                redirect_to root_path
            else
                redirect_to login_path
            end
        end
    end

    def destroy
        reset_session
        redirect_to login_path
    end
     
    private
    
    def auth
    request.env['omniauth.auth']
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
  before_action :authentification_required
    
  def index
        @categories = Category.all
        @brands = Brand.all
        @items = Item.all
        @item = Item.new
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
        render :layout => false
    end

    def create
        @user = User.new
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            redirect_to '/users/new'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/show.html.erb
<h1><%= @brand.name %></h1>

<%= form_tag("/brands/#{@brand.id}", method: :get, id: "brand_items") do %>
    <%= submit_tag("See " + @brand.name + " items") %>
<% end %>

<div id="brandItemsHook"></div>


<%= link_to "Buy an unlisted item", new_brand_item_path(@brand) %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% @category.items.each do |item| %>
    <ul>
        <li><%= link_to item.name, [@category, item] %></li>
    </ul>
<% end %>

<p>
<%= link_to "Buy an unlisted item", new_category_item_path(@category) %>
</p>

app/views/items/_new_item_form.html.erb

    <br>Name:<br>
    <%= f.text_field :name %><br>
    <br>Brand:<br>
    <%= f.text_field :brand_name %><br>
    <br>Category:<br>
    <%= f.text_field :category_name %><br>
    <br>Color:<br>
    <%= f.text_field :color %><br>
    <br>Description:<br>
    <%= f.text_area :description %><br>
    <%= f.submit %>

app/views/items/new.html.erb
<h2> You can't find what you want? Fill out the form to ask your personnal shopper to buy an item on demand </h2>

<% if(@brand) %>
    <%= form_for([@brand, @item], html: {class: :new_item_form, id: :new_item_by_brand }) do |f| %>
        <%= render "items/new_item_form",f: f %>
    <% end %>
<% else %>
    <%= form_for([@category, @item], html: {class: :new_item_form, id: :new_item_by_category }) do |f| %>
        <%= render "items/new_item_form",f: f %>
    <% end %>
<% end %>


<div id= new_item_hook></div>

<script id="new-item-template" type="text/x-handlebars-template">
    <div class="entry">
        <h1>{{name}}</h1>
        <h3>Color: {{color}}</h3>
        <h3>Description: {{description}}</h3>
    </div>
</script>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<h3>Color: </h3>
<%= @item.color %><br>

<h3>Description: </h3>
<%= @item.description %><br>

<h3>Available: </h3>
<%= @item.sold ? "Out of stock" : "In stock" %><br>

app/views/items/sold.html.erb
<h1>Sold items</h1>



<% @items.each do |item| %>
    <ul>
        <li><%= link_to item.name, brand_path(item) %></li>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <%= javascript_include_tag "application" %>
  <h1> Welcome to your personnal shopper portal! </h1>
  <h2> Featured categories </h2>
      <% Category.all.each do |category|  %>
          <ul>
              <li><%= link_to category.name, category_path(category) %></li>
          </ul>
      <% end %>
  </head>

  <body>
    <%= yield %>
  </body>

  <footer><br><br><br>
  <%= link_to "Home", root_path %>

  <%= link_to "Logout", logout_path %>
  </footer>
</html>

app/views/static_pages/index.html.erb

    
<h2> Featured brands </h2>
    <% @brands.each do |brand|  %>
        <ul>
            <li><%= link_to brand.name, brand_path(brand) %></li>
        </ul>
    <% end %>


<%= form_tag("/items/sold", method: :get, id: "sold_items") do %>
    <%= submit_tag("See sold items") %>
<% end %>

<div id="soldItemsHook"></div>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for(@user) do |f| %>
    <%= f.text_field :email, placeholder: "Email" %>
    <%= f.text_field :password, placeholder: "Password" %>
    <%= f.submit %>
<% end %>


<footer>
<%= link_to "Log in to your account", login_path %>
</footer>